# __manifest__.py
{
    'name': 'Extensión de control de calidad para grupo MLA',
    'version': '17.0.0.1',
    'category': 'Quality',
    'summary': 'Custom module to inherit quality point view and add a table',
    'author': 'Your Name',
    'website': 'https://yourwebsite.com',
    'depends': ['quality', 'base', 'quality_control', 'xas_tracking','xas_stock_extend','xas_distributions','quality_control'],
    'data': [
        'security/quality_security.xml',
        'security/ir.model.access.csv',
        'data/mla_characteristics.xml',
        'data/mail_template_data.xml',
        'data/stock_location.xml',
        'wizard/wizard_quality_check.xml',
        'views/res_config_view.xml',
        'views/menus.xml',
        'views/quality_check_view.xml',
        'views/product_template_view.xml',
        'views/product_quality_feature_view.xml',
        'views/product_view.xml',
        'views/product_detail_view.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
    'license': 'LGPL-3',
}
